name = "duty-roster"
account_id = "bd9bb5ff93ae67f993cd3123e1eb02ec"
pages_build_output_dir = "apps/web/.cloudflare"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SERVER_URL = "https://duty-roster-server.duty-roster.workers.dev"
BETTER_AUTH_URL = "https://duty-roster-server.duty-roster.workers.dev"
