name = "duty-roster-server"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
BETTER_AUTH_URL = "https://duty-roster-server.duty-roster.workers.dev/api/auth"
CORS_ORIGIN = "https://duty-roster-8cw.pages.dev"
